### ISSUE TITLE
Incorrect test case

### ISSUE THREAD

**Issue by peterschussheim** [CheckiO-Missions/checkio-task-even-last#19]
Hi,

Trying to solve this challenge and the following test `assert.equal(evenLast([1, 3, 5]), 30, "(1+5)*5=30");` does not adhere to the rules stated in the problem:

> You are given an array of integers. You should find the **sum of the elements with even indexes** (0th, 2nd, 4th...) then multiply this summed number and the final element of the array together.

 [1, 3, 5] are odd numbers and as such, should be ignored, correct?

Thanks,
Peter

**Comment by Bryukh** [comment]
> with even indexes

> [1, 3, 5] are odd numbers

Indexes and elements are not the same.

**Comment by peterschussheim** [comment]
I should have read more carefully...thanks for pointing that out @Bryukh.
